name: thisnotthat
dependencies:
  - python>=3.7
  - panel
  - bokeh
  - numpy>=1.22
  - pandas
  - matplotlib
  - umap-learn
  - hdbscan
  - setuptools
  - glasbey
  - colorcet
  - cmocean
  - pip
  - pip:
      - -e .
