name: thisnotthat
dependencies:
  - python>=3.9
  - panel
  - bokeh
  - numpy>=1.22
  - pandas
  - matplotlib
  - setuptools
  - colorcet
  - pip
  - pip:
      - -e .
      - glasbey
      - hdbscan
      - umap-learn
      - wordcloud
